# Generated by Django 4.2.3 on 2023-07-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superecommercejangoproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
